apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nodeapp-deployment 
  labels: 
    app: nodeapp 
 
 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: nodeapp 
  template: 
    metadata: 
      labels: 
        app: nodeapp 
    spec: 
      containers: 
      - name: nodeserver 
        image: hussain1204/hussain:latest  # Replace with your image name 
        ports: 
        - containerPort: 3000 
